version: "3.8"
services:
  mvn-builder:
    image: maven:3.6.3-jdk-11
    volumes:
      - type: bind
        source: .
        target: /workdir
      - ~/mvn-repo/.m2:/root/.m2
    working_dir:
      /workdir

